/**
 * Pre-built e-commerce Markov baseline used by trajectory-anomaly demos.
 * Generated by simulating 50 normal checkout sessions.
 */
import { MarkovGraph } from '@passiveintent/core';
import type { SerializedMarkovGraph } from '@passiveintent/core';

function build(): SerializedMarkovGraph {
  const g = new MarkovGraph({ maxStates: 100 });
  const funnels: Array<Array<[string, string]>> = [
    [
      ['/home', '/products'],
      ['/products', '/product/item'],
      ['/product/item', '/cart'],
      ['/cart', '/checkout/payment'],
      ['/checkout/payment', '/thank-you'],
    ],
    [
      ['/home', '/pricing'],
      ['/pricing', '/checkout/payment'],
      ['/checkout/payment', '/thank-you'],
    ],
    [
      ['/home', '/products'],
      ['/products', '/product/item'],
      ['/product/item', '/checkout/payment'],
      ['/checkout/payment', '/thank-you'],
    ],
    [
      ['/home', '/blog'],
      ['/blog', '/products'],
      ['/products', '/cart'],
      ['/cart', '/checkout/payment'],
    ],
  ];
  for (let i = 0; i < 50; i++) {
    const funnel = funnels[i % funnels.length];
    for (const [from, to] of funnel) {
      g.incrementTransition(from, to);
    }
  }
  return g.toJSON() as SerializedMarkovGraph;
}

export const ECOMMERCE_BASELINE: SerializedMarkovGraph = build();
